name: Testa Cypress

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start backend
        run: |
          cd backend
          npm run dev &

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Start frontend
        run: |
          cd frontend
          npm run dev &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: electron
